### ISSUE TITLE
Buyer reject shopper (maybe blacklist as well)

### ISSUE THREAD

**Issue by Mercieral** [RH-Groceries/RH-Groceries#28]

**Comment by JJGayso** [comment]
2 Cases of Getting Rejected:

1. Go to shopping, if blacklisted, the list just doesn't show up for you
2. In the "waiting for buyer" modal for shopper, the modal content changes to "Hey, sorry the buyer didn't approve you"

Current Status: 1 Complete, 2 In Progress

**Comment by JJGayso** [comment]
Complete
